-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'senior_accountant'::user_role,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.vendors (
  vendor_id character varying NOT NULL,
  name character varying NOT NULL,
  type USER-DEFINED NOT NULL DEFAULT 'Supplier'::vendor_type,
  tax_id_pin character varying NOT NULL UNIQUE,
  contact_person character varying,
  email character varying,
  phone character varying,
  bank_account character varying,
  vat_treatment USER-DEFINED NOT NULL DEFAULT 'Standard (16%)'::vat_treatment_type,
  wht_type USER-DEFINED NOT NULL DEFAULT '2%'::wht_type,
  currency character varying NOT NULL DEFAULT 'KES'::character varying,
  default_ledger character varying NOT NULL,
  default_department character varying NOT NULL,
  default_cost_centre character varying NOT NULL,
  payment_terms character varying DEFAULT 'Net 30'::character varying,
  status USER-DEFINED NOT NULL DEFAULT 'Active'::vendor_status,
  notes text,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT vendors_pkey PRIMARY KEY (vendor_id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id character varying NOT NULL,
  vendor_name character varying NOT NULL,
  invoice_number character varying NOT NULL,
  cu_invoice_number character varying NOT NULL,
  invoice_date date NOT NULL,
  due_date date NOT NULL,
  subtotal numeric NOT NULL DEFAULT 0.00,
  vat_treatment character varying NOT NULL,
  vat_amount numeric NOT NULL DEFAULT 0.00,
  total numeric NOT NULL DEFAULT 0.00,
  currency character varying NOT NULL DEFAULT 'KES'::character varying,
  wht_type character varying NOT NULL DEFAULT 'Exempt'::character varying,
  wht_amount numeric NOT NULL DEFAULT 0.00,
  cost_centre character varying NOT NULL,
  gl_account character varying NOT NULL,
  department character varying NOT NULL,
  approved_by character varying,
  approval_date timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'Draft'::invoice_status,
  kra_rate numeric DEFAULT 1.0000,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(vendor_id)
);
CREATE TABLE public.wht_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_id uuid,
  vendor_name character varying NOT NULL,
  vendor_pin character varying NOT NULL,
  cu_invoice_number character varying NOT NULL,
  invoice_date date NOT NULL,
  payment_date date NOT NULL,
  gross_amount numeric NOT NULL DEFAULT 0.00,
  wht_rate numeric NOT NULL,
  wht_amount numeric NOT NULL DEFAULT 0.00,
  payment_ref character varying NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'Calculated'::wht_payment_status,
  kra_reference character varying,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT wht_payments_pkey PRIMARY KEY (id),
  CONSTRAINT wht_payments_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id)
);
CREATE TABLE public.gl_accounts (
  code character varying NOT NULL,
  name character varying NOT NULL,
  type USER-DEFINED NOT NULL,
  department character varying NOT NULL,
  cost_centre character varying NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT gl_accounts_pkey PRIMARY KEY (code)
);
CREATE TABLE public.employees (
  id character varying NOT NULL,
  name character varying NOT NULL,
  national_id character varying NOT NULL UNIQUE,
  kra_pin character varying NOT NULL UNIQUE,
  sha_pin character varying,
  grade character varying NOT NULL,
  cost_centre character varying NOT NULL,
  department character varying NOT NULL,
  bank_name character varying NOT NULL,
  bank_account_number character varying NOT NULL,
  base_salary numeric NOT NULL DEFAULT 0.00,
  bonus_commission numeric NOT NULL DEFAULT 0.00,
  fringe_benefit numeric NOT NULL DEFAULT 0.00,
  transport_allowance numeric NOT NULL DEFAULT 0.00,
  arrears numeric NOT NULL DEFAULT 0.00,
  ot_other numeric NOT NULL DEFAULT 0.00,
  voluntary_pension numeric NOT NULL DEFAULT 0.00,
  advances numeric NOT NULL DEFAULT 0.00,
  helb numeric NOT NULL DEFAULT 0.00,
  company_loan numeric NOT NULL DEFAULT 0.00,
  bank_loan numeric NOT NULL DEFAULT 0.00,
  sacco numeric NOT NULL DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT employees_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payroll_runs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  month character varying NOT NULL UNIQUE,
  status USER-DEFINED NOT NULL DEFAULT 'Draft'::payroll_run_status,
  processed_by uuid,
  approved_by uuid,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT payroll_runs_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_runs_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.profiles(id),
  CONSTRAINT payroll_runs_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.payroll_register_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  payroll_run_id uuid NOT NULL,
  employee_id character varying NOT NULL,
  basic_salary numeric NOT NULL DEFAULT 0.00,
  bonus_commission numeric NOT NULL DEFAULT 0.00,
  fringe_benefit numeric NOT NULL DEFAULT 0.00,
  transport_allowance numeric NOT NULL DEFAULT 0.00,
  arrears numeric NOT NULL DEFAULT 0.00,
  ot_other numeric NOT NULL DEFAULT 0.00,
  voluntary_pension numeric NOT NULL DEFAULT 0.00,
  advances numeric NOT NULL DEFAULT 0.00,
  helb numeric NOT NULL DEFAULT 0.00,
  company_loan numeric NOT NULL DEFAULT 0.00,
  bank_loan numeric NOT NULL DEFAULT 0.00,
  sacco numeric NOT NULL DEFAULT 0.00,
  gross_salary numeric NOT NULL DEFAULT 0.00,
  nssf_t1 numeric NOT NULL DEFAULT 420.00,
  nssf_t2 numeric NOT NULL DEFAULT 1740.00,
  shif numeric NOT NULL DEFAULT 0.00,
  ahl numeric NOT NULL DEFAULT 0.00,
  defined_pension_ee numeric NOT NULL DEFAULT 0.00,
  taxable_pay numeric NOT NULL DEFAULT 0.00,
  gross_paye numeric NOT NULL DEFAULT 0.00,
  personal_relief numeric NOT NULL DEFAULT 2400.00,
  nhif_relief numeric NOT NULL DEFAULT 0.00,
  ahl_relief numeric NOT NULL DEFAULT 0.00,
  net_paye numeric NOT NULL DEFAULT 0.00,
  total_deductions numeric NOT NULL DEFAULT 0.00,
  net_pay numeric NOT NULL DEFAULT 0.00,
  employer_pension numeric NOT NULL DEFAULT 0.00,
  nita numeric NOT NULL DEFAULT 50.00,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT payroll_register_entries_pkey PRIMARY KEY (id),
  CONSTRAINT payroll_register_entries_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payroll_register_entries_payroll_run_id_fkey FOREIGN KEY (payroll_run_id) REFERENCES public.payroll_runs(id)
);
CREATE TABLE public.checklist_items (
  id character varying NOT NULL,
  task text NOT NULL,
  assigned_to character varying NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'Pending'::checklist_status,
  completed_date date,
  approver character varying,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT checklist_items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.budgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cost_centre character varying NOT NULL,
  gl_account character varying NOT NULL,
  month character varying NOT NULL,
  budget_amount numeric NOT NULL DEFAULT 0.00,
  actual_amount numeric NOT NULL DEFAULT 0.00,
  created_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  updated_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  CONSTRAINT budgets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.documents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  tag USER-DEFINED NOT NULL,
  storage_path text NOT NULL,
  size integer NOT NULL,
  uploaded_at timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  uploaded_by character varying NOT NULL,
  is_deleted boolean NOT NULL DEFAULT false,
  deletion_reason text,
  CONSTRAINT documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audit_logs (
  id character varying NOT NULL,
  timestamp timestamp with time zone DEFAULT timezone('Africa/Nairobi'::text, now()),
  operator_user character varying NOT NULL,
  action character varying NOT NULL,
  document_ref character varying,
  details text,
  amount numeric,
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);